import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'daos/message_dao.dart';
import 'daos/keyword_dao.dart';
import 'tables/messages.dart';
import 'tables/keywords.dart';
import 'tables/groups.dart';

part 'database.g.dart';

@DriftDatabase(
  tables: [MessageRecords, KeywordRules, MonitoredGroups],
  daos: [MessageDao, KeywordDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_open());
  AppDatabase.forTesting(super.e);

  // `messageDao` and `keywordDao` are inherited as `late final` fields from
  // `_$AppDatabase` (generated by Drift), so they don't need redefining here.

  @override
  int get schemaVersion => 2;

  // v1→v2: add the nullable `jump_key` text column to `message_records`
  // (carries the WeChat contentIntent's jump key, see MessageRecord.jumpKey).
  // The column is nullable, so existing rows are backfilled with NULL and old
  // code that doesn't reference it keeps working.
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await m.addColumn(messageRecords, messageRecords.jumpKey);
          }
        },
      );
}

LazyDatabase _open() {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'ma.sqlite'));
    return NativeDatabase(file);
  });
}
